# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import master.action


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tourpackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False, verbose_name='Active Status')),
                ('delete_status', models.BooleanField(default=False, verbose_name='Delete status')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('modified_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('package_name', models.CharField(max_length=50, verbose_name='Package Name')),
                ('package_description', models.TextField(max_length=1000, verbose_name='Package Description')),
                ('package_location', models.CharField(max_length=50, verbose_name='Location')),
                ('package_photos', models.ImageField(max_length=255, upload_to=master.action.update_image, verbose_name='Photos to Upload')),
                ('package_document', models.FileField(upload_to=master.action.update_file, verbose_name='Package Document')),
                ('no_of_days', models.IntegerField(verbose_name='No. of days')),
                ('no_of_nights', models.IntegerField(verbose_name='No. of nights')),
                ('adult_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Package Cost (Adult)')),
                ('children_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Package Cost (Children)')),
                ('infant_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Package Cost (Infant)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
