# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False, verbose_name='Active Status')),
                ('delete_status', models.BooleanField(default=False, verbose_name='Delete status')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('modified_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('booking_id', models.CharField(max_length=20, verbose_name='Enter Booking Id')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('amount_paying', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paying')),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance Amount')),
                ('payment_mode', models.CharField(choices=[('online', 'ONLINE'), ('cheque/dd', 'CHEQUE/DD'), ('cash', 'CASH')], max_length=100, verbose_name='Payment Mode')),
                ('remarks', models.TextField(verbose_name='Notes, if any')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
