# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 10:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False, verbose_name='Active Status')),
                ('delete_status', models.BooleanField(default=False, verbose_name='Delete status')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('modified_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('customer_name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('customer_mobile', models.BigIntegerField(validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')], verbose_name='Customer Contact No.')),
                ('customer_alt_mobile', models.BigIntegerField(blank=True, null=True, verbose_name='Customer Alternate Contact No.')),
                ('customer_email', models.EmailField(max_length=50, verbose_name='Customer Email ID')),
                ('customer_address', models.TextField(max_length=1000, verbose_name='Customer Address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
