# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('tourpackage', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False, verbose_name='Active Status')),
                ('delete_status', models.BooleanField(default=False, verbose_name='Delete status')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('modified_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('booking_id', models.CharField(max_length=500, null=True, verbose_name='Auto generated booking Id')),
                ('departure_date', models.DateField(verbose_name='Date of Departure')),
                ('arrival_date', models.DateField(verbose_name='Date of Arrival')),
                ('no_of_days', models.IntegerField(verbose_name='No. of days')),
                ('no_of_nights', models.IntegerField(verbose_name='No. of nights')),
                ('no_of_adult', models.IntegerField(verbose_name='No. of adults')),
                ('no_of_children', models.IntegerField(verbose_name='No. of Children')),
                ('no_of_infant', models.IntegerField(verbose_name='No. of Infant')),
                ('total_person', models.IntegerField(verbose_name='Total Person')),
                ('package_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Package Cost')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount (if any)')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Cost')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Paid Amount')),
                ('mealplan', models.CharField(choices=[('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('dinner', 'DINNER')], default=0, max_length=100, verbose_name='Meal Plan')),
                ('mealPlan_type', models.CharField(choices=[('ep', 'EP'), ('cp', 'CP'), ('map', 'MAP'), ('ap', 'AP')], default=0, max_length=100, verbose_name='Meal Plan Type')),
                ('remarks', models.TextField(verbose_name='Notes, if any')),
                ('booking_confirmation_status', models.BooleanField(default=False, verbose_name='Booking Team Confirmation status')),
                ('coordination_confirmation_status', models.BooleanField(default=False, verbose_name='Co-ordination Team Confirmation status')),
                ('finance_confirmation_status', models.BooleanField(default=False, verbose_name='Finance Team Confirmation status')),
                ('accomodation', models.ManyToManyField(to='master.AccomodationStar', verbose_name='Accomodation Type and Star')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='Customer ID')),
                ('mode_of_transport', models.ManyToManyField(to='master.TransportType', verbose_name='Mode of Transport and Type')),
                ('package', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='tourpackage.Tourpackage', verbose_name='Package Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coordination',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('booking.booking',),
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('booking.coordination',),
        ),
    ]
