# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False, verbose_name='Active Status')),
                ('delete_status', models.BooleanField(default=False, verbose_name='Delete status')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('modified_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('places_to_visit', models.CharField(max_length=255, verbose_name='Places to Visit')),
                ('departure_date', models.DateField(verbose_name='Date of Departure')),
                ('arrival_date', models.DateField(verbose_name='Date of Arrival')),
                ('no_of_days', models.IntegerField(help_text='Auto generated by system based on departure and arrival date', null=True, verbose_name='No. of days')),
                ('no_of_nights', models.IntegerField(verbose_name='No. of nights')),
                ('no_of_adult', models.IntegerField(verbose_name='No. of adults')),
                ('no_of_children', models.IntegerField(verbose_name='No. of Children')),
                ('no_of_infant', models.IntegerField(verbose_name='No. of Infant')),
                ('total_person', models.IntegerField(help_text='Auto generated by system based on counting the no. of adult, children and infant', null=True, verbose_name='Total Person')),
                ('mealplan', models.CharField(choices=[('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('dinner', 'DINNER')], max_length=100, verbose_name='Meal Plan')),
                ('mealPlan_type', models.CharField(choices=[('ep', 'EP'), ('cp', 'CP'), ('map', 'MAP'), ('ap', 'AP')], max_length=100, verbose_name='Meal Plan Type')),
                ('remarks', models.TextField(verbose_name='Notes, if any')),
                ('marketing_confirmation_status', models.BooleanField(default=False, verbose_name='Martketing Team Confirmation status')),
                ('accomodation', models.ManyToManyField(to='master.AccomodationStar', verbose_name='Accomodation Type')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='Customer ID')),
                ('mode_of_transport', models.ManyToManyField(to='master.TransportType', verbose_name='Mode of Transport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
