# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='accomodation',
            field=models.ManyToManyField(to='master.AccomodationStarAndType', verbose_name='Accomodation Type'),
        ),
    ]
